### ISSUE TITLE
04# Thresholding/prog02.py: TypeError: Image data cannot be converted to float

### ISSUE THREAD

**Issue by mloskot** [ashwin-pajankar/Python-OpenCV3#5]
At https://www.youtube.com/watch?v=UYmVL1ZXp_w&t=28, you are getting nice visualisations of images in the Spyder. I've tried to run original version of your script (just modified the `path` to the `Dataset` folder), but having no luck:

```
runfile('D:\\workshop\\opencv\\youtube\\04# Thresholding\\prog02.py', wdir='D:\\workshop\\opencv\\youtube\\04# Thresholding')
Traceback (most recent call last):

  File "<ipython-input-6-6dd87a93072a>", line 1, in <module>
    runfile('D:\\workshop\\opencv\\youtube\\04# Thresholding\\prog02.py', wdir='D:\\workshop\\opencv\\youtube\\04# Thresholding')

  File "C:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "D:\workshop\opencv\youtube\04# Thresholding\prog02.py", line 49, in <module>
    main()

  File "D:\workshop\opencv\youtube\04# Thresholding\prog02.py", line 41, in main
    plt.imshow(output[i], cmap='gray')

  File "C:\Anaconda3\lib\site-packages\matplotlib\pyplot.py", line 2699, in imshow
    None else {}), **kwargs)

  File "C:\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 1810, in inner
    return func(ax, *args, **kwargs)

  File "C:\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py", line 5494, in imshow
    im.set_data(X)

  File "C:\Anaconda3\lib\site-packages\matplotlib\image.py", line 634, in set_data
    raise TypeError("Image data cannot be converted to float")

TypeError: Image data cannot be converted to float
```

Using Spyder 3.3.3 installed via Anaconda3

```
(base) C:\>conda --version
conda 4.7.5

(base) C:\>python --version
Python 3.7.3
```

**Comment by mloskot** [comment]
I'm sorry for the false alarm. The issue was due to missing `\` separator as in

```
path = 'C:\\a\\b'
imgpath1 =  path + "cameraman.tif"
```

Surprisingly, ` img = cv2.imread(imgpath1, 0)` for non-existent path returns `None` for `img`, instead of raising an error.
